name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dependencies
      run: sudo apt-get install -y gcc llvm clang libgmp-dev libtommath-dev
    - name: configure
      run: ./configure
    - name: make clean
      run: make clean
    - name: make
      run: make

